### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by davephillips** [martin-lueders/ML-modules#4]
Building with latest git pull (master branch) :

$ make
g++ -fPIC -I../../include -I../../dep/include -DVERSION=dev -MMD -O3 -march=nocona -ffast-math -g -Wall -DARCH_LIN -std=c++11 -c -o build/src/Quant.cpp.o src/Quant.cpp
src/Quant.cpp: In member function ‘virtual void Quant::step()’:
src/Quant.cpp:53:76: error: cannot convert ‘__gnu_cxx::__alloc_traits<std::allocator<rack::Input> >::value_type {aka rack::Input}’ to ‘const float*’ for argument ‘1’ to ‘void stepChannel(const float*, float, float*)’
  stepChannel(inputs[IN1_INPUT], params[AMOUNT1_PARAM], outputs[OUT1_OUTPUT]);
                                                                            ^
src/Quant.cpp:54:76: error: cannot convert ‘__gnu_cxx::__alloc_traits<std::allocator<rack::Input> >::value_type {aka rack::Input}’ to ‘const float*’ for argument ‘1’ to ‘void stepChannel(const float*, float, float*)’
  stepChannel(inputs[IN2_INPUT], params[AMOUNT2_PARAM], outputs[OUT2_OUTPUT]);
                                                                            ^
../../compile.mk:49: recipe for target 'build/src/Quant.cpp.o' failed
make: *** [build/src/Quant.cpp.o] Error 1

I've hit the same error with the modules from luckyxxl and av500. Alas, I have no skills with C++, so I'm pretty lost here. Btw, Andrew suggested that changes in the latest engine.hpp should be looked at. Any advice for a possible fix ?

I'm on Fedora 21 an old distribution, with an old GCC 4.9.2. What can I say, I'm an old guy.

**Comment by martin-lueders** [comment]
The code is still compatible only with the 0.3.2 version of rack. Andrew is currently changing the whole engine, and that requires some more changes in the plugin code. As the binary or rack, which people might download is still 0.3.2, I am currently working on getting them to run with that version. Once I have working 0.3.2 compatible modules, I will start porting to the current development version.

My problem is that I don't have enough time at the moment to even catch up with Andrews code changes.

**Comment by tildebyte** [comment]
Andrew's said he expects lots of API churn until he tags 0.4.0, so that's probably a good target to aim for if your time is limited.

**Comment by martin-lueders** [comment]
Is it working for you now? If so, could you please let me know so I can close the issue.

thanks,
Martin

**Comment by davephillips** [comment]
Hi Martin, Yes, I've successfully built them for 0.3.2. Btw, I'm now maintaining two separate builds for the dev and 0.3.2 branches, so please advise if you need anything tested for either branch.

**Comment by martin-lueders** [comment]
Thanks.

I guess I will just implement the Quantum bug fix for 0.3.2 and then freeze that branch (tag it) and move on to the dev branch, preparing the 0.4.0 release.
